# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'c51-coding-challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for c51-coding-challenge

  target 'c51-coding-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
